#!/bin/bash -x


mkdir /tmp/qbdados

mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb atbl_nd > /tmp/qbdados/mdb-export-atbl_nd-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb atbl_spl > /tmp/qbdados/mdb-export-atbl_spl-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb atblidentifica > /tmp/qbdados/mdb-export-atblidentifica-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb atblprocessa > /tmp/qbdados/mdb-export-atblprocessa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb atbltipoparticipacao > /tmp/qbdados/mdb-export-atbltipoparticipacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbl_bancos > /tmp/qbdados/mdb-export-tbl_bancos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbl_carteiras > /tmp/qbdados/mdb-export-tbl_carteiras-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbl_Devolve > /tmp/qbdados/mdb-export-tbl_Devolve-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbl_msg > /tmp/qbdados/mdb-export-tbl_msg-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblagencia > /tmp/qbdados/mdb-export-tblagencia-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblagenciacontatos > /tmp/qbdados/mdb-export-tblagenciacontatos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblagenda > /tmp/qbdados/mdb-export-tblagenda-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblagendaclassificacao > /tmp/qbdados/mdb-export-tblagendaclassificacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblaliquota > /tmp/qbdados/mdb-export-tblaliquota-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblatveconomica > /tmp/qbdados/mdb-export-tblatveconomica-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblautorizacao > /tmp/qbdados/mdb-export-tblautorizacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblauxiliar1 > /tmp/qbdados/mdb-export-tblauxiliar1-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblbancos > /tmp/qbdados/mdb-export-tblbancos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcidade > /tmp/qbdados/mdb-export-tblcidade-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblclassfiscal > /tmp/qbdados/mdb-export-tblclassfiscal-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblclassfiscal_substituicao > /tmp/qbdados/mdb-export-tblclassfiscal_substituicao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcliente > /tmp/qbdados/mdb-export-tblcliente-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblclientecontatos > /tmp/qbdados/mdb-export-tblclientecontatos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcodtributorigem > /tmp/qbdados/mdb-export-tblcodtributorigem-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranota > /tmp/qbdados/mdb-export-tblcompranota-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranotacons > /tmp/qbdados/mdb-export-tblcompranotacons-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranotaparciais > /tmp/qbdados/mdb-export-tblcompranotaparciais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranotaprod > /tmp/qbdados/mdb-export-tblcompranotaprod-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranotaserv > /tmp/qbdados/mdb-export-tblcompranotaserv-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompras > /tmp/qbdados/mdb-export-tblcompras-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcomprasconsig > /tmp/qbdados/mdb-export-tblcomprasconsig-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcomprasdevolucoes > /tmp/qbdados/mdb-export-tblcomprasdevolucoes-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcomprasprodutos > /tmp/qbdados/mdb-export-tblcomprasprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcomprasprodutos_di_ad > /tmp/qbdados/mdb-export-tblcomprasprodutos_di_ad-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcondpagto > /tmp/qbdados/mdb-export-tblcondpagto-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcondpagtodias > /tmp/qbdados/mdb-export-tblcondpagtodias-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcontrole > /tmp/qbdados/mdb-export-tblcontrole-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbldevolucaoprodutos > /tmp/qbdados/mdb-export-tbldevolucaoprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbldizeresfiscais > /tmp/qbdados/mdb-export-tbldizeresfiscais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblempresa > /tmp/qbdados/mdb-export-tblempresa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblfornecedor > /tmp/qbdados/mdb-export-tblfornecedor-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblfornecedoranking > /tmp/qbdados/mdb-export-tblfornecedoranking-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblfornecedorcontatos > /tmp/qbdados/mdb-export-tblfornecedorcontatos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblfuncionario > /tmp/qbdados/mdb-export-tblfuncionario-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblfuncionariocargos > /tmp/qbdados/mdb-export-tblfuncionariocargos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblkardex > /tmp/qbdados/mdb-export-tblkardex-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbllancamentosregistros > /tmp/qbdados/mdb-export-tbllancamentosregistros-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblmenu > /tmp/qbdados/mdb-export-tblmenu-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblmenusuario > /tmp/qbdados/mdb-export-tblmenusuario-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblmoedas > /tmp/qbdados/mdb-export-tblmoedas-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblmoedascotacao > /tmp/qbdados/mdb-export-tblmoedascotacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnatureza > /tmp/qbdados/mdb-export-tblnatureza-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnaturezaoperacao > /tmp/qbdados/mdb-export-tblnaturezaoperacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnaturezaoperacaocodigos > /tmp/qbdados/mdb-export-tblnaturezaoperacaocodigos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnaturezaoperacaodefault > /tmp/qbdados/mdb-export-tblnaturezaoperacaodefault-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnotasfiscaiscor > /tmp/qbdados/mdb-export-tblnotasfiscaiscor-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnotasfiscaiscorsub > /tmp/qbdados/mdb-export-tblnotasfiscaiscorsub-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnotasfiscaisform > /tmp/qbdados/mdb-export-tblnotasfiscaisform-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnotasfiscaisnumeros > /tmp/qbdados/mdb-export-tblnotasfiscaisnumeros-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnumcompradel > /tmp/qbdados/mdb-export-tblnumcompradel-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnumvendadel > /tmp/qbdados/mdb-export-tblnumvendadel-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblordemproducao > /tmp/qbdados/mdb-export-tblordemproducao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblordemproducaocomponentes > /tmp/qbdados/mdb-export-tblordemproducaocomponentes-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblordemproducaoexcecoes > /tmp/qbdados/mdb-export-tblordemproducaoexcecoes-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblordemproducaomotivo > /tmp/qbdados/mdb-export-tblordemproducaomotivo-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblpais > /tmp/qbdados/mdb-export-tblpais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutos > /tmp/qbdados/mdb-export-tblprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosassociados > /tmp/qbdados/mdb-export-tblprodutosassociados-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosconsignados > /tmp/qbdados/mdb-export-tblprodutosconsignados-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosconsignadosfornecedor > /tmp/qbdados/mdb-export-tblprodutosconsignadosfornecedor-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosdevolvidos > /tmp/qbdados/mdb-export-tblprodutosdevolvidos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosestoque > /tmp/qbdados/mdb-export-tblprodutosestoque-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutoslinha > /tmp/qbdados/mdb-export-tblprodutoslinha-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutoslinhacliente > /tmp/qbdados/mdb-export-tblprodutoslinhacliente-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosprecocliente > /tmp/qbdados/mdb-export-tblprodutosprecocliente-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosreceita > /tmp/qbdados/mdb-export-tblprodutosreceita-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblpromocao > /tmp/qbdados/mdb-export-tblpromocao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblpromocaoprodutos > /tmp/qbdados/mdb-export-tblpromocaoprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblpropostaparametrizada > /tmp/qbdados/mdb-export-tblpropostaparametrizada-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblreducaoicms > /tmp/qbdados/mdb-export-tblreducaoicms-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblregiao > /tmp/qbdados/mdb-export-tblregiao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblrelcliempresa > /tmp/qbdados/mdb-export-tblrelcliempresa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblrelforempresa > /tmp/qbdados/mdb-export-tblrelforempresa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblrelfuncempresa > /tmp/qbdados/mdb-export-tblrelfuncempresa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblremessa > /tmp/qbdados/mdb-export-tblremessa-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblrptcontrole > /tmp/qbdados/mdb-export-tblrptcontrole-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblservicos > /tmp/qbdados/mdb-export-tblservicos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblstatus > /tmp/qbdados/mdb-export-tblstatus-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblsubstituicao > /tmp/qbdados/mdb-export-tblsubstituicao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempbalancete > /tmp/qbdados/mdb-export-tbltempbalancete-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempdemonstrativo > /tmp/qbdados/mdb-export-tbltempdemonstrativo-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempdemonstrativocontaspai > /tmp/qbdados/mdb-export-tbltempdemonstrativocontaspai-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempdemonstrativocruzada > /tmp/qbdados/mdb-export-tbltempdemonstrativocruzada-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempfaturamento > /tmp/qbdados/mdb-export-tbltempfaturamento-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempjuros > /tmp/qbdados/mdb-export-tbltempjuros-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltemplancamento > /tmp/qbdados/mdb-export-tbltemplancamento-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltemplancamentosdiversos > /tmp/qbdados/mdb-export-tbltemplancamentosdiversos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltemplancreg > /tmp/qbdados/mdb-export-tbltemplancreg-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentrada > /tmp/qbdados/mdb-export-tbltempnfentrada-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradaerro > /tmp/qbdados/mdb-export-tbltempnfentradaerro-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradaparciais > /tmp/qbdados/mdb-export-tbltempnfentradaparciais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradaprod > /tmp/qbdados/mdb-export-tbltempnfentradaprod-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradarelacaoconsig > /tmp/qbdados/mdb-export-tbltempnfentradarelacaoconsig-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradaserv > /tmp/qbdados/mdb-export-tbltempnfentradaserv-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempordemproducaoexcecoes > /tmp/qbdados/mdb-export-tbltempordemproducaoexcecoes-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempprodutos > /tmp/qbdados/mdb-export-tbltempprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempreceberpagarprog > /tmp/qbdados/mdb-export-tbltempreceberpagarprog-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempservicos > /tmp/qbdados/mdb-export-tbltempservicos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltemptotalbalancete > /tmp/qbdados/mdb-export-tbltemptotalbalancete-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltipocentrocustos > /tmp/qbdados/mdb-export-tbltipocentrocustos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltipodocumento > /tmp/qbdados/mdb-export-tbltipodocumento-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltipodocumentocarteiras > /tmp/qbdados/mdb-export-tbltipodocumentocarteiras-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltipoparticipacao > /tmp/qbdados/mdb-export-tbltipoparticipacao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltiporecdesp > /tmp/qbdados/mdb-export-tbltiporecdesp-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltransportadora > /tmp/qbdados/mdb-export-tbltransportadora-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltransportadoracoleta > /tmp/qbdados/mdb-export-tbltransportadoracoleta-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltransportadoracontatos > /tmp/qbdados/mdb-export-tbltransportadoracontatos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblundmedida > /tmp/qbdados/mdb-export-tblundmedida-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbluser > /tmp/qbdados/mdb-export-tbluser-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendas > /tmp/qbdados/mdb-export-tblvendas-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasconsig > /tmp/qbdados/mdb-export-tblvendasconsig-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasdevolvidas > /tmp/qbdados/mdb-export-tblvendasdevolvidas-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasfatmateriais > /tmp/qbdados/mdb-export-tblvendasfatmateriais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasfatprod > /tmp/qbdados/mdb-export-tblvendasfatprod-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasfatserv > /tmp/qbdados/mdb-export-tblvendasfatserv-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasfaturadas > /tmp/qbdados/mdb-export-tblvendasfaturadas-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendaspdv > /tmp/qbdados/mdb-export-tblvendaspdv-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasprodutos > /tmp/qbdados/mdb-export-tblvendasprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasservicos > /tmp/qbdados/mdb-export-tblvendasservicos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendedor > /tmp/qbdados/mdb-export-tblvendedor-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblweb > /tmp/qbdados/mdb-export-tblweb-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tempreceberprodserv > /tmp/qbdados/mdb-export-tempreceberprodserv-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb usyscontrol > /tmp/qbdados/mdb-export-usyscontrol-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb usyscontrolador > /tmp/qbdados/mdb-export-usyscontrolador-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb usysmaq > /tmp/qbdados/mdb-export-usysmaq-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb usysnet > /tmp/qbdados/mdb-export-usysnet-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb aversao > /tmp/qbdados/mdb-export-aversao-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblagendaassunto > /tmp/qbdados/mdb-export-tblagendaassunto-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcompranotaerro > /tmp/qbdados/mdb-export-tblcompranotaerro-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblcomprasprodutos_di > /tmp/qbdados/mdb-export-tblcomprasprodutos_di-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblempresaimpostos > /tmp/qbdados/mdb-export-tblempresaimpostos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbllancamentosregistrossecundaria > /tmp/qbdados/mdb-export-tbllancamentosregistrossecundaria-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnotasfiscais > /tmp/qbdados/mdb-export-tblnotasfiscais-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblnumopdel > /tmp/qbdados/mdb-export-tblnumopdel-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblparametro > /tmp/qbdados/mdb-export-tblparametro-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblprodutosfornecedor > /tmp/qbdados/mdb-export-tblprodutosfornecedor-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblreceberpagar > /tmp/qbdados/mdb-export-tblreceberpagar-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblremessaprodutos > /tmp/qbdados/mdb-export-tblremessaprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempdevolucaoprodutos > /tmp/qbdados/mdb-export-tbltempdevolucaoprodutos-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltempnfentradapagto > /tmp/qbdados/mdb-export-tbltempnfentradapagto-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltemprecpag > /tmp/qbdados/mdb-export-tbltemprecpag-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tbltipoparticipacaohistorico > /tmp/qbdados/mdb-export-tbltipoparticipacaohistorico-postgres.sql
mdb-export -b strip -I postgres /home/tux/Downloads/Dropbox/projeto/waretech.com.br/QBDados.mdb tblvendasdatas > /tmp/qbdados/mdb-export-tblvendasdatas-postgres.sql

