INSERT INTO APP.vendedor (id, nome, observacao) VALUES (NEXT VALUE FOR vendedor_seq, 'Carina', 'load.sql')
INSERT INTO APP.cliente (id, vendedor_id, nome) VALUES (NEXT VALUE FOR cliente_seq, (select id from vendedor where nome = 'Carina'), 'Fabio')
INSERT INTO APP.fornecedor (id, nome) VALUES (NEXT VALUE FOR fornecedor_seq, 'Casas Bahia')
INSERT INTO APP.categoria (id, nome) VALUES (NEXT VALUE FOR categoria_seq, 'genérico')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'ORÇAMENTO')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'APROVAÇÃO')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'COMPRA')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'BUSCA DE FORNECEDORES')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'AVALIAÇÃO TÉCNICA')
INSERT INTO APP.proposta_status (id, status) VALUES (NEXT VALUE FOR proposta_status_seq, 'ENTREGA')
INSERT INTO APP.produto (id, fornecedor_id, categoria_id, nome, preco) VALUES (NEXT VALUE FOR produto_seq, (select id from fornecedor where nome = 'Casas Bahia'), (select id from categoria where nome = 'genérico'), 'Ventilador', 1.99)