DROP TABLE IF EXISTS APP.proposta_produto CASCADE
DROP TABLE IF EXISTS APP.proposta CASCADE
DROP TABLE IF EXISTS APP.proposta_status CASCADE
DROP TABLE IF EXISTS APP.produto CASCADE
DROP TABLE IF EXISTS APP.fornecedor CASCADE
DROP TABLE IF EXISTS APP.categoria CASCADE
DROP TABLE IF EXISTS APP.cliente CASCADE
DROP TABLE IF EXISTS APP.vendedor CASCADE

DROP SEQUENCE IF EXISTS APP.vendedor_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.cliente_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.fornecedor_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.categoria_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.produto_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.proposta_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.proposta_status_seq RESTRICT
DROP SEQUENCE IF EXISTS APP.proposta_produto_seq RESTRICT